# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  branches:
    master:
      - step:
          name: 'Deployment to Staging'
          deployment: staging
          script:
            - echo "BEGIN deployment to staging..."
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: 'administrator'
                SERVER: '209.151.151.70'
                COMMAND: '/home/administrator/deploy_scripts/yatchwatch-frontend-staging.sh'
      - step:
          name: 'Deployment to Production'
          deployment: production
          trigger: 'manual'
          script:
            - echo "Your deployment to production script goes here..."
